Description: Template for creating EC2 instance with security group config and ssh, http access, S3 access

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-00ee4df451840fa9d
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: SSHSecurityGroup
        - Ref: HTTPSecurityGroup
      IamInstanceProfile: EC2InstanceProfile

  SSHSecurityGroup:
    Description: SG for ssh acces
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for EC2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  HTTPSecurityGroup:
    Description: SG for http acces
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for EC2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: EC2InstanceProfile
      Path: /
      Roles:
        - Ref: S3Role

  S3Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: S3Policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:*
            Resource: "*"
      Roles:
        - Ref: S3Role

  S3Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: S3Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /

Outputs:
  EC2Instance:
    Description: Public ip
    Value: !GetAtt EC2Instance.PublicIp
  InstanceID:
    Description: The Instance ID
    Value: !Ref EC2Instance

AWSTemplateFormatVersion: 2010-09-09
